steps:
  # ================================================================
  # Frontend Build and Deploy
  # ================================================================
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        API_GATEWAY_URL=$(gcloud run services describe api-gateway --platform=managed --region=southamerica-east1 --format='value(status.url)')
        docker build \
          -t southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/frontend:$SHORT_SHA \
          --build-arg PUBLIC_API_URL=$$API_GATEWAY_URL/api \
          --build-arg PUBLIC_WS_URL=$${API_GATEWAY_URL/https:/wss:}/chat/socket.io \
          --build-arg PUBLIC_SUPABASE_URL=$$SUPABASE_URL \
          --build-arg PUBLIC_SUPABASE_ANON_KEY=$$SUPABASE_ANON_KEY \
          --build-arg NODE_ENV=production \
          --build-arg DEBUG=false \
          ./deal-online-frontend
    id: "build-frontend"
    secretEnv: ["SUPABASE_URL", "SUPABASE_ANON_KEY"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/frontend:$SHORT_SHA",
      ]
    id: "push-frontend"
    waitFor: ["build-frontend"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        API_GATEWAY_URL=$(gcloud run services describe api-gateway --platform=managed --region=southamerica-east1 --format='value(status.url)')
        gcloud run deploy deal-online-frontend \
          --image=southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/frontend:$SHORT_SHA \
          --region=southamerica-east1 \
          --platform=managed \
          --allow-unauthenticated \
          --memory=512Mi \
          --cpu=1 \
          --timeout=300 \
          --port=3000 \
          --set-env-vars="PUBLIC_API_URL=$$API_GATEWAY_URL/api,PUBLIC_WS_URL=$${API_GATEWAY_URL/https:/wss:}/chat/socket.io,NODE_ENV=production,DEBUG=false" \
          --set-secrets="PUBLIC_SUPABASE_URL=SUPABASE_URL:latest,PUBLIC_SUPABASE_ANON_KEY=SUPABASE_ANON_KEY:latest"
    id: "deploy-frontend"
    waitFor: ["push-frontend"]
    secretEnv: ["SUPABASE_URL", "SUPABASE_ANON_KEY"]

  # ================================================================
  # Configurar permisos públicos para el frontend
  # ================================================================
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run services add-iam-policy-binding deal-online-frontend --region=southamerica-east1 --member="allUsers" --role="roles/run.invoker"
    id: "set-frontend-public-permissions"
    waitFor: ["deploy-frontend"]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/SUPABASE_URL/versions/latest
      env: "SUPABASE_URL"
    - versionName: projects/$PROJECT_ID/secrets/SUPABASE_ANON_KEY/versions/latest
      env: "SUPABASE_ANON_KEY"

images:
  - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/frontend:$SHORT_SHA"

options:
  machineType: E2_MEDIUM
  logging: CLOUD_LOGGING_ONLY
timeout: "600s"
