steps:
  # ================================================================
  # Crear instancia de Cloud SQL y configurar RabbitMQ (solo se ejecuta una vez)
  # ================================================================
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Verificar si la instancia ya existe
        if ! gcloud sql instances describe deal-online-db --region=southamerica-east1 2>/dev/null; then
          echo "Creando instancia de Cloud SQL..."
          gcloud sql instances create deal-online-db \
            --database-version=POSTGRES_15 \
            --tier=db-f1-micro \
            --region=southamerica-east1 \
            --storage-type=HDD \
            --storage-size=10GB \
            --root-password=${_DB_PASSWORD}
          
          # Crear usuario
          gcloud sql users create dealuser \
            --instance=deal-online-db \
            --password=${_DB_PASSWORD}
            
          # Crear bases de datos
          gcloud sql databases create auth_db --instance=deal-online-db
          gcloud sql databases create auction_db --instance=deal-online-db  
          gcloud sql databases create chat_db --instance=deal-online-db
        else
          echo "La instancia Cloud SQL ya existe"
        fi

        # Para RabbitMQ usaremos CloudAMQP (más económico que Cloud Tasks)
        echo "RabbitMQ configurado para usar CloudAMQP o servicio externo"
    id: "setup-database"

  # ================================================================
  # Auth Service (Desplegar primero)
  # ================================================================
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/auth-service:$SHORT_SHA",
        "./microservices/auth-service",
      ]
    id: "build-auth-service"
    # No waitFor - puede ejecutarse inmediatamente
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/auth-service:$SHORT_SHA",
      ]
    id: "push-auth-service"
    waitFor: ["build-auth-service"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "auth-service"
      - "--image=southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/auth-service:$SHORT_SHA"
      - "--region=southamerica-east1"
      - "--platform=managed"
      - "--no-allow-unauthenticated"
      - "--memory=256Mi"
      - "--cpu=1"
      - "--timeout=300"
      - "--add-cloudsql-instances=$PROJECT_ID:southamerica-east1:deal-online-db"
      - "--set-env-vars=PORT=3001,DB_HOST=/cloudsql/$PROJECT_ID:southamerica-east1:deal-online-db,DB_PORT=5432,DB_USERNAME=dealuser,DB_DATABASE=auth_db,DB_PASSWORD=${_DB_PASSWORD},JWT_SECRET=${_JWT_SECRET},RABBITMQ_URL=${_RABBITMQ_URL},RABBITMQ_EMAIL_QUEUE=emails_queue"
    id: "deploy-auth-service"
    waitFor: ["push-auth-service", "setup-database"]

  # ================================================================
  # Auction Service (Desplegar segundo)
  # ================================================================
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/auction-service:$SHORT_SHA",
        "./microservices/auction-service",
      ]
    id: "build-auction-service"
    # Puede ejecutarse en paralelo con setup-database
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/auction-service:$SHORT_SHA",
      ]
    id: "push-auction-service"
    waitFor: ["build-auction-service"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "auction-service"
      - "--image=southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/auction-service:$SHORT_SHA"
      - "--region=southamerica-east1"
      - "--platform=managed"
      - "--no-allow-unauthenticated"
      - "--memory=256Mi"
      - "--cpu=1"
      - "--timeout=300"
      - "--add-cloudsql-instances=$PROJECT_ID:southamerica-east1:deal-online-db"
      - "--set-env-vars=PORT=3002,DB_HOST=/cloudsql/$PROJECT_ID:southamerica-east1:deal-online-db,DB_PORT=5432,DB_USERNAME=dealuser,DB_DATABASE=auction_db,DB_PASSWORD=${_DB_PASSWORD},JWT_SECRET=${_JWT_SECRET}"
    id: "deploy-auction-service"
    waitFor: ["push-auction-service", "setup-database"]

  # ================================================================
  # Chat Service (Desplegar tercero)
  # ================================================================
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/chat-service:$SHORT_SHA",
        "./microservices/chat-service",
      ]
    id: "build-chat-service"
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/chat-service:$SHORT_SHA",
      ]
    id: "push-chat-service"
    waitFor: ["build-chat-service"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "chat-service"
      - "--image=southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/chat-service:$SHORT_SHA"
      - "--region=southamerica-east1"
      - "--platform=managed"
      - "--no-allow-unauthenticated"
      - "--memory=256Mi"
      - "--cpu=1"
      - "--timeout=300"
      - "--add-cloudsql-instances=$PROJECT_ID:southamerica-east1:deal-online-db"
      - "--set-env-vars=PORT=3003,DB_HOST=/cloudsql/$PROJECT_ID:southamerica-east1:deal-online-db,DB_PORT=5432,DB_USERNAME=dealuser,DB_DATABASE=chat_db,DB_PASSWORD=${_DB_PASSWORD},JWT_SECRET=${_JWT_SECRET}"
    id: "deploy-chat-service"
    waitFor: ["push-chat-service", "setup-database"]

  # ================================================================
  # Email Service (Puede desplegarse en cualquier momento)
  # ================================================================
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/email-service:$SHORT_SHA",
        "./microservices/email-service",
      ]
    id: "build-email-service"
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/email-service:$SHORT_SHA",
      ]
    id: "push-email-service"
    waitFor: ["build-email-service"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "email-service"
      - "--image=southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/email-service:$SHORT_SHA"
      - "--region=southamerica-east1"
      - "--platform=managed"
      - "--no-allow-unauthenticated"
      - "--memory=256Mi"
      - "--cpu=1"
      - "--timeout=300"
      - "--set-env-vars=PORT=3004,RABBITMQ_URL=${_RABBITMQ_URL},RABBITMQ_EMAIL_QUEUE=emails_queue,EMAIL_USER=${_EMAIL_USER},EMAIL_PASS=${_EMAIL_PASS}"
    id: "deploy-email-service"
    waitFor: ["push-email-service"]

  # ================================================================
  # API Gateway (Desplegar al final)
  # ================================================================
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/api-gateway:$SHORT_SHA",
        "./api-gateway",
      ]
    id: "build-api-gateway"
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/api-gateway:$SHORT_SHA",
      ]
    id: "push-api-gateway"
    waitFor: ["build-api-gateway"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        AUTH_URL=$(gcloud run services describe auth-service --platform=managed --region=southamerica-east1 --format='value(status.url)')
        AUCTION_URL=$(gcloud run services describe auction-service --platform=managed --region=southamerica-east1 --format='value(status.url)')
        CHAT_URL=$(gcloud run services describe chat-service --platform=managed --region=southamerica-east1 --format='value(status.url)')
        gcloud run deploy api-gateway \
          --image="southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/api-gateway:$SHORT_SHA" \
          --region=southamerica-east1 \
          --platform=managed \
          --allow-unauthenticated \
          --memory=512Mi \
          --cpu=1 \
          --timeout=300 \
          --set-env-vars="PORT=3000,AUTH_SERVICE_URL=$$AUTH_URL,AUCTION_SERVICE_URL=$$AUCTION_URL,CHAT_SERVICE_URL=$$CHAT_URL"
    id: "deploy-api-gateway"
    waitFor:
      [
        "push-api-gateway",
        "deploy-auth-service",
        "deploy-auction-service",
        "deploy-chat-service",
      ]

images:
  - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/api-gateway:$SHORT_SHA"
  - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/auth-service:$SHORT_SHA"
  - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/auction-service:$SHORT_SHA"
  - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/chat-service:$SHORT_SHA"
  - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/deal-online-repo/email-service:$SHORT_SHA"

options:
  machineType: E2_MEDIUM
  logging: CLOUD_LOGGING_ONLY
timeout: "1200s"
