# ================================================================
# RED Y VOLÚMENES
# ================================================================
networks:
  deal-network:
    driver: bridge

volumes:
  auth_db_data:
  auction_db_data:
  chat_db_data:
  rabbitmq_data:
  prometheus_data:
  grafana_data:

# ================================================================
# SERVICIOS DE INFRAESTRUCTURA Y MONITOREO
# ================================================================
services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - deal-network
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - deal-network

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: always
    ports:
      - "3005:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - deal-network
    depends_on:
      - prometheus

  # ================================================================
  # BASES DE DATOS DEDICADAS
  # ================================================================
  auth-db:
    image: postgres:14-alpine
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - deal-network

  auction-db:
    image: postgres:14-alpine
    container_name: auction-db
    restart: always
    environment:
      POSTGRES_DB: auction_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - auction_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - deal-network

  chat-db:
    image: postgres:14-alpine
    container_name: chat-db
    restart: always
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - chat_db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - deal-network

  # ================================================================
  # PUNTO DE ENTRADA Y MICROSERVICIOS
  # ================================================================
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "3050:3000" # <-- CORRECCIÓN: Cambiado de 3000 a 3050
    env_file:
      - ./api-gateway/.env
    networks:
      - deal-network
    depends_on:
      - auth-service
      - auction-service
      - chat-service

  auth-service:
    build:
      context: ./microservices/auth-service
    container_name: auth-service
    restart: always
    env_file:
      - ./microservices/auth-service/.env
    networks:
      - deal-network
    depends_on:
      auth-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  auction-service:
    build:
      context: ./microservices/auction-service
    container_name: auction-service
    restart: always
    env_file:
      - ./microservices/auction-service/.env
    networks:
      - deal-network
    depends_on:
      auction-db:
        condition: service_started

  chat-service:
    build:
      context: ./microservices/chat-service
    container_name: chat-service
    restart: always
    env_file:
      - ./microservices/chat-service/.env
    networks:
      - deal-network
    depends_on:
      chat-db:
        condition: service_started

  email-service:
    build:
      context: ./microservices/email-service
    container_name: email-service
    restart: always
    env_file:
      - ./microservices/email-service/.env
    networks:
      - deal-network
    depends_on:
      rabbitmq:
        condition: service_healthy