# ================================================================
# RED Y VOLÚMENES
# ================================================================
networks:
  deal-network:
    driver: bridge

volumes:
  # auth_db_data: # Comentado porque ahora se usa una DB externa (Supabase)
  # auction_db_data: # Comentado porque ahora se usa una DB externa (Supabase)
  # chat_db_data: # Comentado porque ahora se usa una DB externa (Supabase)
  # rabbitmq_data: # Comentado porque ahora se usa un broker externo (CloudAMQP)
  prometheus_data:
  grafana_data:

# ================================================================
# SERVICIOS DE INFRAESTRUCTURA Y MONITOREO
# ================================================================
services:
  # --- El servicio local de RabbitMQ ya no es necesario si usas CloudAMQP ---
  # rabbitmq:
  #   ...
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - deal-network

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: always
    ports:
      - "3005:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - deal-network
    depends_on:
      - prometheus

  # ================================================================
  # PUNTO DE ENTRADA Y MICROSERVICIOS
  # ================================================================
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "3050:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=Ua5+XDbhGIB+FkFO70fPPu0cjPQ1UP5Iqcb4+z0qhYqkIuTs1p1uHWkv+oTDztsDwEanMkwa2WZhNYxgD7TwUA==
    networks:
      - deal-network
    depends_on:
      - auth-service
      - auction-service
      - chat-service

  auth-service:
    build:
      context: ./microservices/auth-service
    container_name: auth-service
    restart: always
    environment:
      - PORT=3001
      - JWT_SECRET=Ua5+XDbhGIB+FkFO70fPPu0cjPQ1UP5Iqcb4+z0qhYqkIuTs1p1uHWkv+oTDztsDwEanMkwa2WZhNYxgD7TwUA==
      # --- URL ACTUALIZADA AL CONNECTION POOLER ---
      - DATABASE_URL=postgresql://postgres.qtmxwmlbaitrjwwkfyyu:asda23drasf43f3@aws-0-sa-east-1.pooler.supabase.com:5432/postgres
      - RABBITMQ_URL=amqps://sylvipgr:PxkPXofuAy3mafqSj3yT9zpIB-u128nc@albatross.rmq.cloudamqp.com/sylvipgr
      - RABBITMQ_EMAIL_QUEUE=emails_queue
    networks:
      - deal-network

  auction-service:
    build:
      context: ./microservices/auction-service
    container_name: auction-service
    restart: always
    environment:
      - PORT=3002
      # --- URL ACTUALIZADA AL CONNECTION POOLER ---
      - DATABASE_URL=postgresql://postgres.bpggeirwhwnqqwbjvxob:sad435sdgdasd@aws-0-us-east-2.pooler.supabase.com:5432/postgres
      - JWT_SECRET=Ua5+XDbhGIB+FkFO70fPPu0cjPQ1UP5Iqcb4+z0qhYqkIuTs1p1uHWkv+oTDztsDwEanMkwa2WZhNYxgD7TwUA==
    networks:
      - deal-network

  chat-service:
    build:
      context: ./microservices/chat-service
    container_name: chat-service
    restart: always
    environment:
      - PORT=3003
      # --- URL ACTUALIZADA AL CONNECTION POOLER ---
      - DATABASE_URL=postgresql://postgres.scqbglnhemejcpngxfcx:ewrwr234rxfv@aws-0-sa-east-1.pooler.supabase.com:5432/postgres
      - JWT_SECRET=Ua5+XDbhGIB+FkFO70fPPu0cjPQ1UP5Iqcb4+z0qhYqkIuTs1p1uHWkv+oTDztsDwEanMkwa2WZhNYxgD7TwUA==
    networks:
      - deal-network

  email-service:
    build:
      context: ./microservices/email-service
    container_name: email-service
    restart: always
    environment:
      - RABBITMQ_URL=amqps://sylvipgr:PxkPXofuAy3mafqSj3yT9zpIB-u128nc@albatross.rmq.cloudamqp.com/sylvipgr
      - RABBITMQ_EMAIL_QUEUE=emails_queue
      - EMAIL_FROM_NAME=Deal Online
      - EMAIL_FROM_ADDRESS=sebasdelpm@gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - EMAIL_USER=sebasdelpm@gmail.com
      - EMAIL_PASS=rvfbornjpqfhpgnq
    networks:
      - deal-network
